// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Events.Infrastructure.Data;

#nullable disable

namespace Modules.Events.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EventsDBContext))]
    [Migration("20241117173430_Add_Version_For_ActivitySeat")]
    partial class Add_Version_For_ActivitySeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("events")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Activities", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1096),
                            Date = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1097),
                            Deleted = false,
                            Name = "Ram",
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1096),
                            VenueId = new Guid("c82171f1-aa5f-4434-b0cd-90a8bedeb4af")
                        },
                        new
                        {
                            Id = new Guid("7933e0d3-4905-4d2c-b9a1-c20ead197883"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1098),
                            Date = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1099),
                            Deleted = false,
                            Name = "Circus",
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1098),
                            VenueId = new Guid("ef0716cb-54d8-4ddb-8d25-b2a8cb61f026")
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityOffers", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cee58eef-219c-4551-9031-4ae68a17dd8b"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Amount = 250.0,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1115),
                            Deleted = false,
                            PriceType = 2,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1115)
                        },
                        new
                        {
                            Id = new Guid("53e2569d-3ea4-4b47-9480-46952765c0c9"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Amount = 500.0,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1118),
                            Deleted = false,
                            PriceType = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1118)
                        },
                        new
                        {
                            Id = new Guid("440f0129-8982-4c77-97e9-76cd3efa67d0"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Amount = 800.0,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1120),
                            Deleted = false,
                            PriceType = 3,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1120)
                        },
                        new
                        {
                            Id = new Guid("630dd83c-78f3-4e84-b2dd-01bbc52093bd"),
                            ActivityId = new Guid("7933e0d3-4905-4d2c-b9a1-c20ead197883"),
                            Amount = 50.5,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1123),
                            Deleted = false,
                            PriceType = 2,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1123)
                        },
                        new
                        {
                            Id = new Guid("edafbcfe-d72b-4b31-89ad-47cff341b8ee"),
                            ActivityId = new Guid("7933e0d3-4905-4d2c-b9a1-c20ead197883"),
                            Amount = 100.5,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1125),
                            Deleted = false,
                            PriceType = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1125)
                        },
                        new
                        {
                            Id = new Guid("6b0514ab-1eac-41cd-89b5-f4d0660789b7"),
                            ActivityId = new Guid("7933e0d3-4905-4d2c-b9a1-c20ead197883"),
                            Amount = 200.30000000000001,
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1127),
                            Deleted = false,
                            PriceType = 3,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1127)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SeatId");

                    b.ToTable("ActivitySeats", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28eeaa98-3068-4a7a-8b6e-4457d81d5312"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1148),
                            Deleted = false,
                            SeatId = new Guid("9553dfdd-34cf-4a1b-a9fd-98f6c282fe46"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1148)
                        },
                        new
                        {
                            Id = new Guid("d4016119-36b7-459a-a79f-534f5d69efb3"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1152),
                            Deleted = false,
                            SeatId = new Guid("38862315-7946-499c-a4e8-1dae5221a6fd"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1152)
                        },
                        new
                        {
                            Id = new Guid("433cf7f1-ca84-46fe-9eed-d33124b84acd"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1156),
                            Deleted = false,
                            SeatId = new Guid("f0b63081-812f-4901-8016-422ef2437cc9"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1156)
                        },
                        new
                        {
                            Id = new Guid("194b2efc-02c8-45ab-a375-408e65f30c4a"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1159),
                            Deleted = false,
                            SeatId = new Guid("f137e8cc-b2ba-48ce-9573-53c9559f006f"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1159)
                        },
                        new
                        {
                            Id = new Guid("c85d23cd-61e9-476b-b177-f64ed29dc0d5"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1162),
                            Deleted = false,
                            SeatId = new Guid("a336f3aa-f729-45c3-83be-db6825482152"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1162)
                        },
                        new
                        {
                            Id = new Guid("5928bf55-e20a-418c-9835-d94dba6fb95d"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1165),
                            Deleted = false,
                            SeatId = new Guid("2d803fe6-255b-418a-9b1d-acd9e97f7dba"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1165)
                        },
                        new
                        {
                            Id = new Guid("69971097-4471-4175-ac39-e6d5f5dbfc07"),
                            ActivityId = new Guid("8b5fa894-dfcf-4bb4-a605-5f99985c3805"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1167),
                            Deleted = false,
                            SeatId = new Guid("2eeafcb1-08ad-4ef1-8ce9-89234c3dd251"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1167)
                        },
                        new
                        {
                            Id = new Guid("087b509d-1ada-492e-a9c7-ed3e917bb2fb"),
                            ActivityId = new Guid("7933e0d3-4905-4d2c-b9a1-c20ead197883"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1171),
                            Deleted = false,
                            SeatId = new Guid("60593976-4fd5-430b-8f59-e4b402f56f12"),
                            State = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1172)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeatOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivitySeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityOfferId");

                    b.HasIndex("ActivitySeatId")
                        .IsUnique();

                    b.ToTable("ActivitySeatOffers", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c0c96fb-1a79-49c3-837e-21992973603f"),
                            ActivityOfferId = new Guid("cee58eef-219c-4551-9031-4ae68a17dd8b"),
                            ActivitySeatId = new Guid("28eeaa98-3068-4a7a-8b6e-4457d81d5312"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1191),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1191)
                        },
                        new
                        {
                            Id = new Guid("a45516ba-9bd0-43d5-a591-284c34fe914b"),
                            ActivityOfferId = new Guid("cee58eef-219c-4551-9031-4ae68a17dd8b"),
                            ActivitySeatId = new Guid("d4016119-36b7-459a-a79f-534f5d69efb3"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1195),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1195)
                        },
                        new
                        {
                            Id = new Guid("d59b9cc7-efae-4c7f-9349-865127dd7bfb"),
                            ActivityOfferId = new Guid("cee58eef-219c-4551-9031-4ae68a17dd8b"),
                            ActivitySeatId = new Guid("433cf7f1-ca84-46fe-9eed-d33124b84acd"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1197),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1197)
                        },
                        new
                        {
                            Id = new Guid("e6b4879e-947d-46d9-8189-c6a820d1ff8a"),
                            ActivityOfferId = new Guid("53e2569d-3ea4-4b47-9480-46952765c0c9"),
                            ActivitySeatId = new Guid("194b2efc-02c8-45ab-a375-408e65f30c4a"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1199),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1199)
                        },
                        new
                        {
                            Id = new Guid("6a1adaa4-3cd9-417f-ae02-53a5f2887e81"),
                            ActivityOfferId = new Guid("53e2569d-3ea4-4b47-9480-46952765c0c9"),
                            ActivitySeatId = new Guid("c85d23cd-61e9-476b-b177-f64ed29dc0d5"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1201),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1201)
                        },
                        new
                        {
                            Id = new Guid("6a2ed8c8-61c3-4de7-a840-6e79011f481c"),
                            ActivityOfferId = new Guid("440f0129-8982-4c77-97e9-76cd3efa67d0"),
                            ActivitySeatId = new Guid("5928bf55-e20a-418c-9835-d94dba6fb95d"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1202),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1203)
                        },
                        new
                        {
                            Id = new Guid("2b6de77f-4970-42e8-b8e6-e1335e870da7"),
                            ActivityOfferId = new Guid("440f0129-8982-4c77-97e9-76cd3efa67d0"),
                            ActivitySeatId = new Guid("69971097-4471-4175-ac39-e6d5f5dbfc07"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1204),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1204)
                        },
                        new
                        {
                            Id = new Guid("cb0b008c-6a1e-45a5-81a0-87c46f899a77"),
                            ActivityOfferId = new Guid("630dd83c-78f3-4e84-b2dd-01bbc52093bd"),
                            ActivitySeatId = new Guid("087b509d-1ada-492e-a9c7-ed3e917bb2fb"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1206),
                            Deleted = false,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1206)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Rows", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3eb84460-8144-4340-9577-5c4d3c90f532"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1028),
                            Deleted = false,
                            Number = 1,
                            SectionId = new Guid("b6a3c9e9-b7f5-425d-a716-d2d7f788f423"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1028)
                        },
                        new
                        {
                            Id = new Guid("6013c720-74c8-4285-bfe4-e7104890f7fa"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1032),
                            Deleted = false,
                            Number = 2,
                            SectionId = new Guid("b6a3c9e9-b7f5-425d-a716-d2d7f788f423"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1032)
                        },
                        new
                        {
                            Id = new Guid("ed7b3f11-4a85-446f-b5e0-679033f0b0a1"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1033),
                            Deleted = false,
                            Number = 1,
                            SectionId = new Guid("38dc4132-780d-4fc1-8f66-1badbd06e6f5"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1034)
                        },
                        new
                        {
                            Id = new Guid("3421eb72-8ead-45f8-9204-975d00e3f030"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1036),
                            Deleted = false,
                            Number = 1,
                            SectionId = new Guid("51440082-c6a0-43d9-8a92-c4e0318f24cd"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1036)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.ToTable("Seats", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9553dfdd-34cf-4a1b-a9fd-98f6c282fe46"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1056),
                            Deleted = false,
                            Number = 1,
                            RowId = new Guid("3eb84460-8144-4340-9577-5c4d3c90f532"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1057)
                        },
                        new
                        {
                            Id = new Guid("38862315-7946-499c-a4e8-1dae5221a6fd"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1060),
                            Deleted = false,
                            Number = 2,
                            RowId = new Guid("3eb84460-8144-4340-9577-5c4d3c90f532"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1061)
                        },
                        new
                        {
                            Id = new Guid("f0b63081-812f-4901-8016-422ef2437cc9"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1062),
                            Deleted = false,
                            Number = 3,
                            RowId = new Guid("3eb84460-8144-4340-9577-5c4d3c90f532"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1062)
                        },
                        new
                        {
                            Id = new Guid("f137e8cc-b2ba-48ce-9573-53c9559f006f"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1066),
                            Deleted = false,
                            Number = 1,
                            RowId = new Guid("6013c720-74c8-4285-bfe4-e7104890f7fa"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1067)
                        },
                        new
                        {
                            Id = new Guid("a336f3aa-f729-45c3-83be-db6825482152"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1068),
                            Deleted = false,
                            Number = 2,
                            RowId = new Guid("6013c720-74c8-4285-bfe4-e7104890f7fa"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1069)
                        },
                        new
                        {
                            Id = new Guid("2d803fe6-255b-418a-9b1d-acd9e97f7dba"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1071),
                            Deleted = false,
                            Number = 1,
                            RowId = new Guid("ed7b3f11-4a85-446f-b5e0-679033f0b0a1"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1071)
                        },
                        new
                        {
                            Id = new Guid("2eeafcb1-08ad-4ef1-8ce9-89234c3dd251"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1072),
                            Deleted = false,
                            Number = 2,
                            RowId = new Guid("ed7b3f11-4a85-446f-b5e0-679033f0b0a1"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1072)
                        },
                        new
                        {
                            Id = new Guid("60593976-4fd5-430b-8f59-e4b402f56f12"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1074),
                            Deleted = false,
                            Number = 1,
                            RowId = new Guid("3421eb72-8ead-45f8-9204-975d00e3f030"),
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1074)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Sections", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6a3c9e9-b7f5-425d-a716-d2d7f788f423"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1003),
                            Deleted = false,
                            Number = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1004),
                            VenueId = new Guid("c82171f1-aa5f-4434-b0cd-90a8bedeb4af")
                        },
                        new
                        {
                            Id = new Guid("38dc4132-780d-4fc1-8f66-1badbd06e6f5"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1006),
                            Deleted = false,
                            Number = 2,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1006),
                            VenueId = new Guid("c82171f1-aa5f-4434-b0cd-90a8bedeb4af")
                        },
                        new
                        {
                            Id = new Guid("51440082-c6a0-43d9-8a92-c4e0318f24cd"),
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1010),
                            Deleted = false,
                            Number = 1,
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(1010),
                            VenueId = new Guid("ef0716cb-54d8-4ddb-8d25-b2a8cb61f026")
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Venues", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c82171f1-aa5f-4434-b0cd-90a8bedeb4af"),
                            BuildNumber = "15A",
                            City = "Lodz",
                            Country = "Poland",
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(896),
                            Deleted = false,
                            Name = "Arena",
                            Street = "Kolobzesk",
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(898)
                        },
                        new
                        {
                            Id = new Guid("ef0716cb-54d8-4ddb-8d25-b2a8cb61f026"),
                            BuildNumber = "98",
                            City = "Gdansk",
                            Country = "Poland",
                            Created = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(908),
                            Deleted = false,
                            Name = "GHT Arena",
                            Street = "Opolska",
                            Updated = new DateTime(2024, 11, 17, 17, 34, 30, 68, DateTimeKind.Utc).AddTicks(908)
                        });
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Venue", "Venue")
                        .WithMany("Activities")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.Activity", "Activity")
                        .WithMany("ActivityOffers")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.Activity", "Activity")
                        .WithMany("ActivitySeats")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Seat", "Seat")
                        .WithMany("ActivitySeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeatOffer", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.ActivityOffer", "ActivityOffer")
                        .WithMany("ActivitySeatOffers")
                        .HasForeignKey("ActivityOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Events.Data.Entities.ActivitySeat", "ActivitySeat")
                        .WithOne("ActivitySeatOffer")
                        .HasForeignKey("Modules.Events.Data.Entities.ActivitySeatOffer", "ActivitySeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActivityOffer");

                    b.Navigation("ActivitySeat");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Section", "Section")
                        .WithMany("Rows")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Row", "Row")
                        .WithMany("Seats")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.Navigation("ActivityOffers");

                    b.Navigation("ActivitySeats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.Navigation("ActivitySeatOffers");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.Navigation("ActivitySeatOffer");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.Navigation("ActivitySeats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Venue", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
