// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Events.Data;

#nullable disable

namespace Modules.Events.Data.Migrations
{
    [DbContext(typeof(EventsDBContext))]
    partial class EventsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("events")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Activities", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityOffers", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivitySeatOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SeatId");

                    b.ToTable("ActivitySeats", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeatOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivitySeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityOfferId");

                    b.HasIndex("ActivitySeatId")
                        .IsUnique();

                    b.ToTable("ActivitySeatOffers", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Rows", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.ToTable("Seats", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Sections", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Venues", "events");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Venue", "Venue")
                        .WithMany("Activities")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.Activity", "Activity")
                        .WithMany("ActivityOffers")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.Activity", "Activity")
                        .WithMany("ActivitySeats")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Seat", "Seat")
                        .WithMany("ActivitySeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeatOffer", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.ActivityOffer", "ActivityOffer")
                        .WithMany("ActivitySeatOffers")
                        .HasForeignKey("ActivityOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Events.Data.Entities.ActivitySeat", "ActivitySeat")
                        .WithOne("ActivitySeatOffer")
                        .HasForeignKey("Modules.Events.Data.Entities.ActivitySeatOffer", "ActivitySeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActivityOffer");

                    b.Navigation("ActivitySeat");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Section", "Section")
                        .WithMany("Rows")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Row", "Row")
                        .WithMany("Seats")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.HasOne("Modules.Events.Data.Entities.VenueManifest.Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.Activity", b =>
                {
                    b.Navigation("ActivityOffers");

                    b.Navigation("ActivitySeats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivityOffer", b =>
                {
                    b.Navigation("ActivitySeatOffers");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.ActivitySeat", b =>
                {
                    b.Navigation("ActivitySeatOffer");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Row", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Seat", b =>
                {
                    b.Navigation("ActivitySeats");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Section", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Modules.Events.Data.Entities.VenueManifest.Venue", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
